version: '3.9'

services:

    database:
        hostname: influx
        restart: always
        container_name: influx
        image: influxdb:latest

        volumes:
            - /tmp/docker/influxdb/etc/influxdb:/etc/influxdb:ro
            - /tmp/docker/influxdb/var:/var/lib/influxdb

        environment:
            # - INFLUXDB_ADMIN_USER=admin
            # - INFLUXDB_ADMIN_PASSWORD=qwerty12345
            # - INFLUXDB_DB=telegraf
            # - INFLUXDB_USER=telegraf
            # - INFLUXDB_ADMIN_ENABLED=true

            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=admin
            - DOCKER_INFLUXDB_INIT_PASSWORD=qwerty12345
            - DOCKER_INFLUXDB_INIT_ORG=test_organization
            - DOCKER_INFLUXDB_INIT_BUCKET=my_bucket
            - DOCKER_INFLUXDB_INIT_RETENTION=1w
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token

        ports:
            - 8089:8089/udp
            - 8086:8086
